Add "type" field to all the variables
rancher/tf-rancher-up pull request #127
Opened 2024-05-20 11:20 UTC by BreakingPitt

## Summary

This pull request addresses the requirements outlined in Issue #38 by adding the missing "type" field to all the Terraform variables. 

This ensures that each variable has a defined type, improving code clarity and preventing potential configuration errors.

## Related Issue

Issue #38

## Additional Notes
Descriptions and sensitive flags have been added where necessary.
Validation conditions were included to ensure correct values for certain variables.
Please review the changes and provide feedback or approval for merging.

2024-05-21 07:53 UTC, BreakingPitt commented
Hey I would like to test this, to see that the changes doesn't break anything, but seems the Drone job for somereason is broken.

2025-05-15 08:09 UTC, glovecchi0 requested changes
Is it possible to review the PR with the current codebase? So as to resolve the conflicts.

PS: an issue should then be opened to ensure that the variable description has the same style in all modules and recipes.

2025-12-16 15:05 UTC, glovecchi0 commented
Hi @BreakingPitt,
Could you please review this PR from scratch? So we can proceed with approval.

Sorry it's been sitting idle for a while.

TIA!

2026-04-14 09:49 UTC, closed without merging

2026-04-14 09:49 UTC, glovecchi0 commented
#238