Review of AWS infra modules and tests
rancher/tf-rancher-up pull request #158
Opened 2024-07-31 10:28 UTC by glovecchi0

Division of the PR #145

2024-08-26 02:20 UTC, dkeightley commented
Thanks @glovecchi0, for a long term approach is there any hesitance to using official modules for the VPC resources?
  * https://github.com/terraform-aws-modules/terraform-aws-vpc?tab=readme-ov-file#usage

These modules follow best practices with dependency management etc., but will also unlock all the flexibility to users and reduce maintenance from our side without repeating code.

Is there a reason to move the module into `../ec2/`? This will break existing environments and seems to be the only module nested further into a directory, or am I overlooking some info on why that needs to happen?

2024-08-26 07:29 UTC, glovecchi0 commented
> Thanks @glovecchi0, for a long term approach is there any hesitance to using official modules for the VPC resources?
> 
> * https://github.com/terraform-aws-modules/terraform-aws-vpc?tab=readme-ov-file#usage
> 
> These modules follow best practices with dependency management etc., but will also unlock all the flexibility to users and reduce maintenance from our side without repeating code.
> 
> Is there a reason to move the module into `../ec2/`? This will break existing environments and seems to be the only module nested further into a directory, or am I overlooking some info on why that needs to happen?

Hey @dkeightley!! 😄 
The idea of ​​creating the ec2 folder (as also done for Google forms) is to give the possibility of creating the various infra resources in different locations, for order and cleanliness.
This is also a stylistic choice; it can be changed.

It makes absolute sense to use the official modules of the various Cloud Providers; I think the same goes for EC2, etc. not just for the Network.
Maybe we can open an FR for this.

2024-08-27 17:18 UTC, suryaboorlu commented
@glovecchi0 Overall, everything looks solid to me. I've included a few suggestions that you might find helpful—please take a look and see if they resonate with you.

2024-09-02 00:17 UTC, dkeightley requested changes
@glovecchi0 I'm still a bit confused here, every recipe will need to be updated to refer to the nested `../ec2` directory, also there will be a few variable/output changes. What testing has been done?

Eg: https://github.com/rancher/tf-rancher-up/blob/fix/review-aws-infra-modules/recipes/upstream/aws/rke2/main.tf#L15

The previous output.tf appears to be left behind, does that need to be deleted?
  * https://github.com/rancher/tf-rancher-up/blob/fix/review-aws-infra-modules/modules/infra/aws/outputs.tf

nit: can we avoid commented code wherever possible
  * https://github.com/rancher/tf-rancher-up/blob/fix/review-aws-infra-modules/modules/infra/aws/ec2/main.tf#L45

2025-01-09 13:30 UTC, closed without merging