Consistency for rancher_password default value
rancher/tf-rancher-up pull request #163
Opened 2024-08-04 22:35 UTC by dkeightley

Update `rancher_password` default value to be consistent between all recipes, also reduces the number of required variables to use a recipe

2024-08-05 21:26 UTC, dkeightley commented
I removed the two-password approach while making these consistent amongst recipes/modules, if we'd still prefer an option for a separate password for the helm install, and bootstraping rancher I can revert to keeping both variables

2024-08-12 06:37 UTC, sandipnikale commented on recipes/upstream/aws/k3s/variables.tf
Just curious why are we having 2 variables 'rancher_bootstrap_password' and 'rancher_password'?
when we run recipe without specifying password in .tfvar file assuming it should use the default one but seems its conflicting, see below error
 Error: Invalid function argument
│
│   on variables.tf line 135, in variable "rancher_password":
│  135:     condition     = length(var.rancher_password) >= 12
│     ├────────────────
│     │ while calling length(value)
│     │ var.rancher_password is null
│
│ Invalid value for "value" parameter: argument must not be null.

2024-08-12 06:41 UTC, sandipnikale requested changes
Seems we are not able to run scripts without specifying rancher password in .tfvar  as var.rancher_password default is null, it throws below: 
` Invalid value for "value" parameter: argument must not be null.`

2024-08-12 21:49 UTC, dkeightley commented on recipes/upstream/aws/k3s/variables.tf
Thanks @sandipnikale, we did previously have one password, I noticed a change added a password for bootstrap (helm install), and a separate Rancher admin password, so I kept this as-is to preserve that feature.

The above change also made it mandatory to set an admin password, the bootstrap password will have a default however. This makes sense I figure from a security perspective so that public-facing endpoints (the Rancher dashboard) don't have a predictable default admin password.

Hopefully the password requirement (default = null) became clear as part of this PR with the move of `rancher_password` variable to the "required variables" section in the tfvars.example, this PR also made the variable and tfvars.example consistent where possible among all modules. Let me know if you have any other thoughts on the changes.

2024-08-21 11:37 UTC, sandipnikale approved these changes
Looks good, thanks for the PR

2024-08-26 02:07 UTC, merged